apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: todoapp
  labels:
    app: busybox
spec:
  containers:
    - name: busybox
      image: ikulyk404/busyboxplus:curl
      command:
        - sleep
        - "3600"
