apiVersion: v1
kind: Pod
metadata:
  name: todoapp-pod
  namespace: todoapp
  labels:
    app: todoapp-pod
spec:
  containers:
    - name: todoapp-pod
      image: andriikhamaza/todoapp:3.0.0
      ports:
        - containerPort: 8080 # ?
      livenessProbe:
        httpGet:
          path: /api/health
          port: 8080
        initialDelaySeconds: 60
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: /api/ready
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 5